/*
PROGRAMA CREADO EL DIA 11/04/24 EN PROCESO DE CREACION AL DIA 12/04/24

PROGRAMA: BUSQUEDA_EQUIPO1    --> BUSQUEDA EN ESPINA DE PESCADO

EL OBJETIVO DEL PROGRAMA ES REALIZAR UNA BUSQUEDA EN UN MAPA EN FORMA DE ESPINA 
DE PESCADO, IMPLICA CREAR UN AGENTE INTELIGENTE QUE REALICE LA BUSQUEDA DE UN
OBJETIVO SIN SABER DONDE ESTA Y CON ESTO ELIMINAR POSIBLES ACCIONES
QUE NO TENGAN NECESIDAD AL ENCONTRAR EL OBJETIVO, ENTONCES, EL PROGRAMA
REALIZARA EL MAPEO, Y EL AGENTE COMENZARA A BUSCAR HASTA ENCONTRAR EL OBJETIVO
Y VISITAR LA SALIDA DE MANERA INMEDIATA, SIN REVISAR EL RESTO DEL MAPA.

*/


//ESTA VENTANA ES PARA EL CEREBRO DE INICIO DEL PROGRAMA.
package Principal;

import javax.swing.JOptionPane;

public class cerebro extends Mapa {
    
    public static void main(String[]args){
        Mapa a = new Mapa();
        int arr[] = a.creacion();
        JOptionPane.showMessageDialog(null,"El mapeo esta de la siguiente manera: "+a.mapa);
    }
}
